CC = g++
CC_FLAGS = -std=c++17 -Wall -O2 -I../openssl-1_0_2u/include/
LD_LIBS = -pthread -lboost_system -lboost_regex -L../openssl-1_0_2u -lssl -lcrypto -ldl -lz -static -static-libstdc++
# -ltcmalloc_minimal 

EXEC = asbs
SOURCES = $(wildcard *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)

# Main target
$(EXEC): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXEC) $(LD_LIBS)

%.o: %.cpp
	$(CC) -c $(CC_FLAGS) $< -o $@

clean:
	rm -rf $(EXEC) $(OBJECTS)


